default persistent.unlocked_replay_scenes = set()
init python:

    class ReplayItem:
        def __init__(self, thumbs, replay, name, replay_number = None):
            self.thumbs = thumbs
            self.replay = replay
            self.name = name
            self.replay_number = replay_number
        @property
        def thumbnail_image(self):
         thumbnail = "images/gallery thumbnails/" + self.thumbs + "_t" + ".webp"
         if renpy.loadable(thumbnail):
          return thumbnail
         return self.thumbs

    #add replay items here format below
    #Replay_items.append(ReplayItem(["the thumbnail"], "the_label_from_code", "brief description"))
    Replay_items = []
    Replay_items.append(ReplayItem("alex doggy1","replay_alex_doggy","Will and Alex doggy"))
    Replay_items.append(ReplayItem("kim fondle 1","kim_pov1","Kim in Will's home"))
    Replay_items.append(ReplayItem("kim and jamie handjob 1","replay_kim_jamie_handjob","Kim and Jamie handjob"))
    Replay_items.append(ReplayItem("kim and alex chat 1","replay_kim_and_alex_chat","Kim and Alex chat"))
    Replay_items.append(ReplayItem("kim spies on alex and will 1","replay_kim_spies_on_will","Kim spies on Will"))
    Replay_items.append(ReplayItem("jamieandwill cuddlenight","replay_sleepover","Jamie and Will sleepover"))
    Replay_items.append(ReplayItem("will bulgeselfie","will_and_diane_text1","Will and Diane chat 1"))
    Replay_items.append(ReplayItem("kim dildo1","kim_pov2","Kim sucks a Dildo"))
    Replay_items.append(ReplayItem("diane lewd2","diane_pov1","Will and Diane chat 2"))
    Replay_items.append(ReplayItem("kim and jamie standing","kim_date3","Kim and Jamie date"))
    Replay_items.append(ReplayItem("diane nude text","will_and_diane_text2","Will and Diane sexting"))
    Replay_items.append(ReplayItem("diane and will side 1","will_and_diane_sex1","Will and Diane app date"))
    Replay_items.append(ReplayItem("kim and alex chat 2","kim_dildo1","Kim rides a dildo"))
    Replay_items.append(ReplayItem("diane and will frontdoor 2","will_and_diane_sex1_aftermath","Diane and Will sex aftermath"))
    Replay_items.append(ReplayItem("kim and jamie doggy 1","football_aftermath","Football aftermath"))
    Replay_items.append(ReplayItem("kim and will bj bulge","party","Kim and Will at party and after events"))
    Replay_items.append(ReplayItem("diane will carry 0","diane_and_will_breastmilk","Diane and Will breastmilk"))
    Replay_items.append(ReplayItem("kim bbc masturbating","kim_browsing","Kim bbc masturbating"))
    Replay_items.append(ReplayItem("william kim dance 1","kim_and_will_date","Kim and Will date and party"))
    Replay_items.append(ReplayItem("william kim room","jamie_peek","Jamie cleaning job"))
    Replay_items.append(ReplayItem("gelatomoosoomay","jamie_necklace","Jamie necklace gift and date/afterdate"))
    Replay_items.append(ReplayItem("diane boobjob 1","will_and_diane_date","Will and Diane date"))
    Replay_items.append(ReplayItem("diane blanket","dianewill","Will and Diane sleeping together"))
    Replay_items.append(ReplayItem("ice cream 1","morning","Kim and Jamie spending the day together"))
    Replay_items.append(ReplayItem("jamie bench 1","hangout","Jamie goes to the gym"))
    Replay_items.append(ReplayItem("diane mirror selfie","will_and_diane_date2"," Will and Diane second date"))
    Replay_items.append(ReplayItem("diane mirror selfie 2","jamie_date","Will and Diane second date Jamie pov"))
    Replay_items.append(ReplayItem("kim cow 1","kim_cow_bikini","Kim tries cow set"))
    Replay_items.append(ReplayItem("diane sweat","diane_and_jamie_date","Diane and Jamie convention"))
    Replay_items.append(ReplayItem("will and jamie park","will_and_jamie_park","will and jamie at park together"))
    Replay_items.append(ReplayItem("kim kabedon 1","kim_degrade","kim degrade Jamie"))
    Replay_items.append(ReplayItem("diane cock kiss 1","diane_ass","Will scared Diane"))
    Replay_items.append(ReplayItem("diane will tent 1","camping_start","camping day one"))
    Replay_items.append(ReplayItem("nice view","day_2_morning","camping day two"))
    Replay_items.append(ReplayItem("shadow doggy","split_jamie_pov","split Jamie's pov"))
    Replay_items.append(ReplayItem("cabin art","kim_and_will_camp","split Kim's pov"))
    Replay_items.append(ReplayItem("gelatomoosoomay","meetup","after camp"))
    Replay_items.append(ReplayItem("car seggs 1","park_secret","Kim and Will signed a pact"))
    Replay_items.append(ReplayItem("kim bathroom bj1","class_excuse","kim taking blowjob/storage classes"))
    Replay_items.append(ReplayItem("kim love ho 1","kim_love_ho","Kim love hotel with Will"))
    Replay_items.append(ReplayItem("diane first bj1","diane_bj","Diane first blowjob"))
    Replay_items.append(ReplayItem("jamie finger 4","ice_cream","Jamie exploration"))
    Replay_items.append(ReplayItem("will diane kiss 2","diane_party","Diane party"))
    Replay_items.append(ReplayItem("gelatomoosoomay","kim_pissy","Branching pact"))
    Replay_items.append(ReplayItem("gelatomoosoomay","christmas_party","christmas party"))
    Replay_items.append(ReplayItem("kim will christmas 1","netorase_christmas","netorase christmas"))
    Replay_items.append(ReplayItem("kim will christmas 1","netorare_christmas","netorare christmas"))
    Replay_items.append(ReplayItem("gelatomoosoomay","christmas_eve","christmas eve"))
    Replay_items.append(ReplayItem("diane christmas sex 1","diane_suspects","Diane christmas seggs"))
    Replay_items.append(ReplayItem("kim dinner grin","valentine_intro","Valentine date"))
    Replay_items.append(ReplayItem("diane dinner smile","diane_valentine_date","Diane valentine date"))
    Replay_items.append(ReplayItem("jamie cheer shy","kim_jamie_valentines_sex","Kim and Jamie valentine sex"))
    Replay_items.append(ReplayItem("kim cow bj 1","william_kim_valentines_nts","William and Kim valentine date NTS"))
    Replay_items.append(ReplayItem("kim cow bj 1","william_kim_valentines_ntr","William and Kim valentine date NTR"))
    Replay_items.append(ReplayItem("nts jamie 1","diane_discovers_jamie_ntr","Diane discovers Jamie NTR"))
    Replay_items.append(ReplayItem("threesome cosplay","diane_discovers_jamie_sissy","Diane discovers Jamie SISSY"))
    Replay_items.append(ReplayItem("diane peek","diane_discovers","Diane discovers"))
    Replay_items.append(ReplayItem("jamie cowgirl 1","kim_convince_sissy","Jamie cowgirl"))
    Replay_items.append(ReplayItem("kim cabin sleep 1","kim_convince_nts","Kim convince NTS"))
    Replay_items.append(ReplayItem("kimdiane fit","family_park","Family park!"))
    Replay_items.append(ReplayItem("kim diane bj 1","dinner_ntr","Dinner NTR"))
    Replay_items.append(ReplayItem("kim diane kiss","dinner_ntr_jamie_pov","Dinner NTR Jamie pov"))
    Replay_items.append(ReplayItem("nts restaurant","nts_arrangement","Kim NTS arrangement"))
    Replay_items.append(ReplayItem("nts restaurant","ntr_start_jamie_pov","Kim NTR"))
    Replay_items.append(ReplayItem("jamie lift 2","will bonding","Will and Jamie bonding"))
    Replay_items.append(ReplayItem("gelatomoosoomay","island_vacay","Island vacay start"))
    Replay_items.append(ReplayItem("kim quickie 1","plane_bj","Kim's plane blowjob"))
    Replay_items.append(ReplayItem("gelatomoosoomay","airplane_cont","airplane landed to Island"))
    Replay_items.append(ReplayItem("diane afterparty 1","diane_island_night","Diane island night"))
    Replay_items.append(ReplayItem("volleyball yk","diane_day_two","Island day two"))
    Replay_items.append(ReplayItem("isle bathroom sex 1","island_hideaway_jamie_pov","Island hideaway"))
    Replay_items.append(ReplayItem("gelatomoosoomay","island_day_two_cont","Island day two continues"))
    Replay_items.append(ReplayItem("gelatomoosoomay","island_day_three","Island day three"))
    Replay_items.append(ReplayItem("french sex 1","diane_gangbang","Diane first gangbang"))
    Replay_items.append(ReplayItem("skydive","island_day_four","Island day four"))
    Replay_items.append(ReplayItem("island stack","kim_island_threesome_start_nts","Kim Island threesome NTS"))
    Replay_items.append(ReplayItem("divided jamie ntr 1","kim_island_threesome_start_ntr","Kim Island threesome NTR"))
    Replay_items.append(ReplayItem("green jamie 1","island_fifth_day","Island fifth day"))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    # Replay_items.append(ReplayItem("","",""))
    Replay_items.append(ReplayItem("alex sex 1", "party_alex_invite_ntr", "Alex and Kim's island party"))
    Replay_items.append(ReplayItem("trio party 1", "party_alex_invite_nts", "Kim missing out on the party"))
    Replay_items.append(ReplayItem("jamie ponder 1", "foreign_date", "Jamie's Date with the foreigner"))
    Replay_items.append(ReplayItem("ky plane 1", "kim_vs_yelena_plane", "Kim and Yelena's battle of wits"))
    Replay_items.append(ReplayItem("diane plane bj 1", "diane_plane_bj", "Diane airplane BJ"))
    Replay_items.append(ReplayItem("diane door mad", "missing_william_jamie", "Diane misses William (Jamie POV)"))
    Replay_items.append(ReplayItem("diane door mad", "missing_william", "Diane misses William (Diane POV)"))
    Replay_items.append(ReplayItem("kim jamie mirror 1", "caging_up", "Jamie wears a cage"))
    Replay_items.append(ReplayItem("push down 1", "catselfie", "Will Takes Jamie's Picture"))
    Replay_items.append(ReplayItem("jamie will diner 1", "tcg_cont", "Will takes \"Jenny\" on a Date"))
    Replay_items.append(ReplayItem("jamie plap 1", "wplaps", "Kim punishes Jamie for ignoring her"))
    Replay_items.append(ReplayItem("jamie frott 1", "rocknstone", "Will and Jamie Sword Fight"))
    Replay_items.append(ReplayItem("jamie mirror lingerie", "kim_punishment", "Kim takes \"Jenny\" on a Date"))
    Replay_items.append(ReplayItem("raven pic 1", "axe", "The group goes to a convention while cosplaying"))
    Replay_items.append(ReplayItem("kim succumb 1", "kim_touch", "Kim's First Creampie"))
    Replay_items.append(ReplayItem("kim succumb 1", "jamie_delivery", "Kim's First Creampie (Jamie POV)"))
    Replay_items.append(ReplayItem("gelatomoosoomay","jamie_and_yelena","Jamie finds a job"))
    Replay_items.append(ReplayItem("gelatomoosoomay","jamie_library","Jamie month anniversary"))
    Replay_items.append(ReplayItem("yelena kabedon 1","yelena_moves","Yelena vs cass"))
    Replay_items.append(ReplayItem("gelatomoosoomay","library_hangout","Yelena genius intuition"))
    Replay_items.append(ReplayItem("gelatomoosoomay","yelena_proposal","Yelena's proposal"))
    Replay_items.append(ReplayItem("yelena kiss 1","yelena_fam","dinner with Yelena's family"))
    Replay_items.append(ReplayItem("gelatomoosoomay","yelena_arrives","Yelena trip invite"))
    Replay_items.append(ReplayItem("yelena costume","yelena_christmas","Yelena christmas"))
    Replay_items.append(ReplayItem("yelena dinner grin","yelena_date","Yelena valentine date"))
    Replay_items.append(ReplayItem("gelatomoosoomay","diane_discovers_jamie_yelena","Jamie chats with Yelena"))
    Replay_items.append(ReplayItem("yelena fit","yelena_boxes","Yelena spends time with Jamie"))
    Replay_items.append(ReplayItem("yelena lotion 0","island_vacay","island vacay"))
    Replay_items.append(ReplayItem("yelena davui 1","yelena_island_accept","Yelena with family at vacay"))
    Replay_items.append(ReplayItem("tv tease 1","tv_tease","Kim TV tease"))
    Replay_items.append(ReplayItem("diane jamie watch 5","jamie_witnesses","Jamie helps Will (NTS)"))
    Replay_items.append(ReplayItem("diane will 69 1","diane_wwe_before","Diane WWE"))
    Replay_items.append(ReplayItem("yelena dressup 3","yelena_secret","Yelena secret"))
    Replay_items.append(ReplayItem("kim diane throatswab 1","jamie_finds_out","Kim cheating whore"))
    # Replay_items.append(ReplayItem("","",""))


    for replay_item in Replay_items:
     replay_item.replay_number = Replay_items.index(replay_item) + 1

     
# a black background screen for the selection
image black = "#000000"
